#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "gcp.h"
#include "gtin.h"

const struct {
    int low; 
    int high; 
    GtinCompanyPrefixRange range; 
} gs1_company_prefix[] = {
    {300, 379, GS1_COMPANY_PREFIX_FRANCE_RANGE},
    {380, 380, GS1_COMPANY_PREFIX_BULGARIA_RANGE},
    {381, 381, GS1_COMPANY_PREFIX_KOSOVO_RANGE},
    {383, 383, GS1_COMPANY_PREFIX_SLOVENIJA_RANGE},
    {385, 385, GS1_COMPANY_PREFIX_CROATIA_RANGE},
    {387, 387, GS1_COMPANY_PREFIX_BOSNIA_HERZEGOVINA_RANGE},
    {389, 389, GS1_COMPANY_PREFIX_MONTENEGRO_RANGE},
    {450, 459, GS1_COMPANY_PREFIX_JAPAN_RANGE},
    {460, 469, GS1_COMPANY_PREFIX_RUSSIA_RANGE},
    {470, 470, GS1_COMPANY_PREFIX_KYRGYZSTAN_RANGE},
    {471, 471, GS1_COMPANY_PREFIX_CHINESE_TAIPEI_RANGE},
    {472, 472, GS1_COMPANY_PREFIX_VIETNAM_RANGE},
    {473, 473, GS1_COMPANY_PREFIX_ARMENIA_RANGE},
    {474, 474, GS1_COMPANY_PREFIX_ESTONIA_RANGE},
    {475, 475, GS1_COMPANY_PREFIX_LATVIA_RANGE},
    {476, 476, GS1_COMPANY_PREFIX_AZERBAIJAN_RANGE},
    {477, 477, GS1_COMPANY_PREFIX_LITHUANIA_RANGE},
    {478, 478, GS1_COMPANY_PREFIX_UZBEKISTAN_RANGE},
    {479, 479, GS1_COMPANY_PREFIX_SRI_LANKA_RANGE},
    {480, 480, GS1_COMPANY_PREFIX_PHILIPPINES_RANGE},
    {481, 481, GS1_COMPANY_PREFIX_BELARUS_RANGE},
    {482, 482, GS1_COMPANY_PREFIX_UKRAINE_RANGE},
    {483, 483, GS1_COMPANY_PREFIX_TURKMENISTAN_RANGE},
    {484, 484, GS1_COMPANY_PREFIX_MOLDOVA_RANGE},
    {485, 485, GS1_COMPANY_PREFIX_ARMENIA_RANGE},
    {486, 486, GS1_COMPANY_PREFIX_GEORGIA_RANGE},
    {487, 487, GS1_COMPANY_PREFIX_KAZAKSTAN_RANGE},
    {488, 488, GS1_COMPANY_PREFIX_TAJIKISTAN_RANGE},
    {489, 489, GS1_COMPANY_PREFIX_HONG_KONG_RANGE},
    {490, 499, GS1_COMPANY_PREFIX_JAPAN_RANGE},
    {500, 509, GS1_COMPANY_PREFIX_UK_RANGE},
    {520, 521, GS1_COMPANY_PREFIX_GREECE_RANGE},
    {528, 528, GS1_COMPANY_PREFIX_LEBANON_RANGE},
    {529, 529, GS1_COMPANY_PREFIX_CYPRUS_RANGE},
    {530, 530, GS1_COMPANY_PREFIX_ALBANIA_RANGE},
    {531, 531, GS1_COMPANY_PREFIX_MACEDONIA_RANGE},
    {535, 535, GS1_COMPANY_PREFIX_MALTA_RANGE},
    {539, 539, GS1_COMPANY_PREFIX_IRELAND_RANGE},
    {540, 549, GS1_COMPANY_PREFIX_BELGIUM_LUXEMBOURG_RANGE},
    {560, 560, GS1_COMPANY_PREFIX_PORTUGAL_RANGE},
    {569, 569, GS1_COMPANY_PREFIX_ICELAND_RANGE},
    {570, 579, GS1_COMPANY_PREFIX_DENMARK_RANGE},
    {590, 590, GS1_COMPANY_PREFIX_POLAND_RANGE},
    {594, 594, GS1_COMPANY_PREFIX_ROMANIA_RANGE},
    {599, 599, GS1_COMPANY_PREFIX_HUNGARY_RANGE},
    {600, 601, GS1_COMPANY_PREFIX_SOUTH_AFRICA_RANGE},
    {603, 603, GS1_COMPANY_PREFIX_GHANA_RANGE},
    {604, 604, GS1_COMPANY_PREFIX_SENEGAL_RANGE},
    {605, 605, GS1_COMPANY_PREFIX_UGANDA_RANGE},
    {606, 606, GS1_COMPANY_PREFIX_ANGOLA_RANGE},
    {607, 607, GS1_COMPANY_PREFIX_OMAN_RANGE},
    {608, 608, GS1_COMPANY_PREFIX_BAHRAIN_RANGE},
    {609, 609, GS1_COMPANY_PREFIX_MAURITIUS_RANGE},
    {610, 610, GS1_COMPANY_PREFIX_MANAGED_BY_GS1_GLOBAL_OFFICE_RANGE},
    {611, 611, GS1_COMPANY_PREFIX_MOROCCO_RANGE},
    {613, 613, GS1_COMPANY_PREFIX_ALGERIA_RANGE},
    {614, 614, GS1_COMPANY_PREFIX_MANAGED_BY_GS1_GLOBAL_OFFICE_RANGE},
    {615, 615, GS1_COMPANY_PREFIX_NIGERIA_RANGE},
    {616, 616, GS1_COMPANY_PREFIX_KENYA_RANGE},
    {617, 617, GS1_COMPANY_PREFIX_CAMEROON_RANGE},
    {618, 618, GS1_COMPANY_PREFIX_COTE_DIVOIRE_RANGE},
    {619, 619, GS1_COMPANY_PREFIX_TUNISIA_RANGE},
    {620, 620, GS1_COMPANY_PREFIX_TANZANIA_RANGE},
    {621, 621, GS1_COMPANY_PREFIX_SYRIA_RANGE},
    {622, 622, GS1_COMPANY_PREFIX_EGYPT_RANGE},
    {623, 623, GS1_COMPANY_PREFIX_MANAGED_BY_GS1_GLOBAL_OFFICE_RANGE},
    {624, 624, GS1_COMPANY_PREFIX_LIBYA_RANGE},
    {625, 625, GS1_COMPANY_PREFIX_JORDAN_RANGE},
    {626, 626, GS1_COMPANY_PREFIX_IRAN_RANGE},
    {627, 627, GS1_COMPANY_PREFIX_KUWAIT_RANGE},
    {628, 628, GS1_COMPANY_PREFIX_SAUDI_ARABIA_RANGE},
    {629, 629, GS1_COMPANY_PREFIX_EMIRATES_RANGE},
    {630, 630, GS1_COMPANY_PREFIX_QATAR_RANGE},
    {631, 631, GS1_COMPANY_PREFIX_NAMIBIA_RANGE},
    {632, 632, GS1_COMPANY_PREFIX_RWANDA_RANGE},
    {640, 649, GS1_COMPANY_PREFIX_FINLAND_RANGE},
    {680, 681, GS1_COMPANY_PREFIX_CHINA_RANGE},
    {690, 699, GS1_COMPANY_PREFIX_CHINA_RANGE},
    {700, 709, GS1_COMPANY_PREFIX_NORWAY_RANGE},
    {729, 729, GS1_COMPANY_PREFIX_ISRAEL_RANGE},
    {730, 739, GS1_COMPANY_PREFIX_SWEDEN_RANGE},
    {740, 740, GS1_COMPANY_PREFIX_GUATEMALA_RANGE},
    {741, 741, GS1_COMPANY_PREFIX_EL_SALVADOR_RANGE},
    {742, 742, GS1_COMPANY_PREFIX_HONDURAS_RANGE},
    {743, 743, GS1_COMPANY_PREFIX_NICARAGUA_RANGE},
    {744, 744, GS1_COMPANY_PREFIX_COSTA_RICA_RANGE},
    {745, 745, GS1_COMPANY_PREFIX_PANAMA_RANGE},
    {746, 746, GS1_COMPANY_PREFIX_REPUBLICA_DOMINICANA_RANGE},
    {750, 750, GS1_COMPANY_PREFIX_MEXICO_RANGE},
    {754, 755, GS1_COMPANY_PREFIX_CANADA_RANGE},
    {758, 758, GS1_COMPANY_PREFIX_MANAGED_BY_GS1_GLOBAL_OFFICE_RANGE},
    {759, 759, GS1_COMPANY_PREFIX_VENEZUELA_RANGE},
    {760, 769, GS1_COMPANY_PREFIX_SWITZERLAND_RANGE},
    {770, 771, GS1_COMPANY_PREFIX_COLOMBIA_RANGE},
    {773, 773, GS1_COMPANY_PREFIX_URUGUAY_RANGE},
    {775, 775, GS1_COMPANY_PREFIX_PERU_RANGE},
    {777, 777, GS1_COMPANY_PREFIX_BOLIVIA_RANGE},
    {778, 779, GS1_COMPANY_PREFIX_ARGENTINA_RANGE},
    {780, 780, GS1_COMPANY_PREFIX_CHILE_RANGE},
    {784, 784, GS1_COMPANY_PREFIX_PARAGUAY_RANGE},
    {786, 786, GS1_COMPANY_PREFIX_ECUADOR_RANGE},
    {789, 790, GS1_COMPANY_PREFIX_BRASIL_RANGE},
    {800, 839, GS1_COMPANY_PREFIX_ITALY_RANGE},
    {840, 849, GS1_COMPANY_PREFIX_SPAIN_RANGE},
    {850, 850, GS1_COMPANY_PREFIX_CUBA_RANGE},
    {858, 858, GS1_COMPANY_PREFIX_SLOVAKIA_RANGE},
    {859, 859, GS1_COMPANY_PREFIX_CZECH_RANGE},
    {860, 860, GS1_COMPANY_PREFIX_SERBIA_RANGE},
    {865, 865, GS1_COMPANY_PREFIX_MONGOLIA_RANGE},
    {867, 867, GS1_COMPANY_PREFIX_NORTH_KOREA_RANGE},
    {868, 869, GS1_COMPANY_PREFIX_TURKIYE_RANGE},
    {870, 879, GS1_COMPANY_PREFIX_NETHERLANDS_RANGE},
    {880, 881, GS1_COMPANY_PREFIX_SOUTH_KOREA_RANGE},
    {883, 883, GS1_COMPANY_PREFIX_MYANMAR_RANGE},
    {884, 884, GS1_COMPANY_PREFIX_CAMBODIA_RANGE},
    {887, 887, GS1_COMPANY_PREFIX_LAOS_RANGE},
    {885, 885, GS1_COMPANY_PREFIX_THAILAND_RANGE},
    {888, 888, GS1_COMPANY_PREFIX_SINGAPORE_RANGE},
    {890, 890, GS1_COMPANY_PREFIX_INDIA_RANGE},
    {893, 893, GS1_COMPANY_PREFIX_VIETNAM_RANGE},
    {894, 894, GS1_COMPANY_PREFIX_MANAGED_BY_GS1_GLOBAL_OFFICE_RANGE},
    {896, 896, GS1_COMPANY_PREFIX_PAKISTAN_RANGE},
    {899, 899, GS1_COMPANY_PREFIX_INDONESIA_RANGE},
    {900, 919, GS1_COMPANY_PREFIX_AUSTRIA_RANGE},
    {930, 939, GS1_COMPANY_PREFIX_AUSTRALIA_RANGE},
    {940, 949, GS1_COMPANY_PREFIX_NEW_ZEALAND_RANGE},
    {951, 951, GS1_COMPANY_PREFIX_GLOBAL_OFFICE_RANGE},
    {952, 952, GS1_COMPANY_PREFIX_DEMONSTRATION_RANGE},
    {955, 955, GS1_COMPANY_PREFIX_MALAYSIA_RANGE},
    {958, 958, GS1_COMPANY_PREFIX_MACAU_RANGE},
    {959, 959, GS1_COMPANY_PREFIX_TAIWAN_RANGE},
    {960, 969, GS1_COMPANY_PREFIX_GLOBAL_OFFICE_RANGE},
    {977, 977, GS1_COMPANY_PREFIX_SERIAL_PUBLICATION_RANGE},
    {978, 979, GS1_COMPANY_PREFIX_BOOKLAND_RANGE},
    {980, 980, GS1_COMPANY_PREFIX_REFUND_RECEIPT_RANGE},
    {981, 983, GS1_COMPANY_PREFIX_COUPON_RANGE},
    {99, 99, GS1_COMPANY_PREFIX_COUPON_RANGE}
};


static GtinCompanyPrefixRange lookup_company_prefix(int prefix) {
    const static int gs1_company_prefix_count = sizeof(gs1_company_prefix) / sizeof(gs1_company_prefix[0]);
    for (int i = 0; i < gs1_company_prefix_count; i++) {
        if (prefix >= gs1_company_prefix[i].low && prefix <= gs1_company_prefix[i].high) {
            return gs1_company_prefix[i].range;
        }
    }
    return GS1_COMPANY_PREFIX_NONE; // Not found
}

char* GTIN_CompanyPrefixToString(GtinCompanyPrefixRange range) {
    switch (range) {
        case GS1_COMPANY_PREFIX_ALBANIA_RANGE: return "Albania";
        case GS1_COMPANY_PREFIX_ALGERIA_RANGE: return "Algeria";
        case GS1_COMPANY_PREFIX_ANGOLA_RANGE: return "Angola";
        case GS1_COMPANY_PREFIX_ARGENTINA_RANGE: return "Argentina";
        case GS1_COMPANY_PREFIX_ARMENIA_RANGE: return "Armenia";
        case GS1_COMPANY_PREFIX_AUSTRALIA_RANGE: return "Australia";
        case GS1_COMPANY_PREFIX_AUSTRIA_RANGE: return "Austria";
        case GS1_COMPANY_PREFIX_AZERBAIJAN_RANGE: return "Azerbaijan";
        case GS1_COMPANY_PREFIX_BAHRAIN_RANGE: return "Bahrain";
        case GS1_COMPANY_PREFIX_BELARUS_RANGE: return "Belarus";
        case GS1_COMPANY_PREFIX_BELGIUM_LUXEMBOURG_RANGE: return "Belgium/Luxembourg";
        case GS1_COMPANY_PREFIX_BOLIVIA_RANGE: return "Bolivia";
        case GS1_COMPANY_PREFIX_BOOKLAND_RANGE: return "Bookland (ISBN)";
        case GS1_COMPANY_PREFIX_BOSNIA_HERZEGOVINA_RANGE: return "Bosnia and Herzegovina";
        case GS1_COMPANY_PREFIX_BRASIL_RANGE: return "Brasil";
        case GS1_COMPANY_PREFIX_BULGARIA_RANGE: return "Bulgaria";
        case GS1_COMPANY_PREFIX_CAMBODIA_RANGE: return "Cambodia";
        case GS1_COMPANY_PREFIX_CAMEROON_RANGE: return "Cameroon";
        case GS1_COMPANY_PREFIX_CANADA_RANGE: return "Canada";
        case GS1_COMPANY_PREFIX_CHILE_RANGE: return "Chile";
        case GS1_COMPANY_PREFIX_CHINA_RANGE: return "China";
        case GS1_COMPANY_PREFIX_CHINESE_TAIPEI_RANGE: return "Chinese Taipei";
        case GS1_COMPANY_PREFIX_COLOMBIA_RANGE: return "Colombia";
        case GS1_COMPANY_PREFIX_COSTA_RICA_RANGE: return "Costa Rica";
        case GS1_COMPANY_PREFIX_COTE_DIVOIRE_RANGE: return "Côte d'Ivoire";
        case GS1_COMPANY_PREFIX_COUPON_RANGE: return "Coupon";
        case GS1_COMPANY_PREFIX_CROATIA_RANGE: return "Croatia";
        case GS1_COMPANY_PREFIX_CUBA_RANGE: return "Cuba";
        case GS1_COMPANY_PREFIX_CYPRUS_RANGE: return "Cyprus";
        case GS1_COMPANY_PREFIX_CZECH_RANGE: return "Czech Republic";
        case GS1_COMPANY_PREFIX_DEMONSTRATION_RANGE: return "Demonstration";
        case GS1_COMPANY_PREFIX_DENMARK_RANGE: return "Denmark";
        case GS1_COMPANY_PREFIX_ECUADOR_RANGE: return "Ecuador";
        case GS1_COMPANY_PREFIX_EGYPT_RANGE: return "Egypt";
        case GS1_COMPANY_PREFIX_EL_SALVADOR_RANGE: return "El Salvador";
        case GS1_COMPANY_PREFIX_EMIRATES_RANGE: return "United Arab Emirates";
        case GS1_COMPANY_PREFIX_ESTONIA_RANGE: return "Estonia";
        case GS1_COMPANY_PREFIX_FINLAND_RANGE: return "Finland";
        case GS1_COMPANY_PREFIX_FRANCE_RANGE: return "France";
        case GS1_COMPANY_PREFIX_GEORGIA_RANGE: return "Georgia";
        case GS1_COMPANY_PREFIX_GHANA_RANGE: return "Ghana";
        case GS1_COMPANY_PREFIX_GLOBAL_OFFICE_RANGE: return "Global Office";
        case GS1_COMPANY_PREFIX_GREECE_RANGE: return "Greece";
        case GS1_COMPANY_PREFIX_GUATEMALA_RANGE: return "Guatemala";
        case GS1_COMPANY_PREFIX_HONDURAS_RANGE: return "Honduras";
        case GS1_COMPANY_PREFIX_HONG_KONG_RANGE: return "Hong Kong";
        case GS1_COMPANY_PREFIX_HUNGARY_RANGE: return "Hungary";
        case GS1_COMPANY_PREFIX_ICELAND_RANGE: return "Iceland";
        case GS1_COMPANY_PREFIX_INDIA_RANGE: return "India";
        case GS1_COMPANY_PREFIX_INDONESIA_RANGE: return "Indonesia";
        case GS1_COMPANY_PREFIX_IRAN_RANGE: return "Iran";
        case GS1_COMPANY_PREFIX_IRELAND_RANGE: return "Ireland";
        case GS1_COMPANY_PREFIX_ISRAEL_RANGE: return "Israel";
        case GS1_COMPANY_PREFIX_ITALY_RANGE: return "Italy";
        case GS1_COMPANY_PREFIX_JAPAN_RANGE: return "Japan";
        case GS1_COMPANY_PREFIX_JORDAN_RANGE: return "Jordan";
        case GS1_COMPANY_PREFIX_KAZAKSTAN_RANGE: return "Kazakhstan";
        case GS1_COMPANY_PREFIX_KENYA_RANGE: return "Kenya";
        case GS1_COMPANY_PREFIX_KOSOVO_RANGE: return "Kosovo";
        case GS1_COMPANY_PREFIX_KUWAIT_RANGE: return "Kuwait";
        case GS1_COMPANY_PREFIX_KYRGYZSTAN_RANGE: return "Kyrgyzstan";
        case GS1_COMPANY_PREFIX_LAOS_RANGE: return "Laos";
        case GS1_COMPANY_PREFIX_LATVIA_RANGE: return "Latvia";
        case GS1_COMPANY_PREFIX_LEBANON_RANGE: return "Lebanon";
        case GS1_COMPANY_PREFIX_LIBYA_RANGE: return "Libya";
        case GS1_COMPANY_PREFIX_LITHUANIA_RANGE: return "Lithuania";
        case GS1_COMPANY_PREFIX_MACAU_RANGE: return "Macau";
        case GS1_COMPANY_PREFIX_MACEDONIA_RANGE: return "Macedonia";
        case GS1_COMPANY_PREFIX_MALAYSIA_RANGE: return "Malaysia";
        case GS1_COMPANY_PREFIX_MALTA_RANGE: return "Malta";
        case GS1_COMPANY_PREFIX_MANAGED_BY_GS1_GLOBAL_OFFICE_RANGE: return "Managed by GS1 Global Office";
        case GS1_COMPANY_PREFIX_MAURITIUS_RANGE: return "Mauritius";
        case GS1_COMPANY_PREFIX_MEXICO_RANGE: return "Mexico";
        case GS1_COMPANY_PREFIX_MOLDOVA_RANGE: return "Moldova";
        case GS1_COMPANY_PREFIX_MONGOLIA_RANGE: return "Mongolia";
        case GS1_COMPANY_PREFIX_MONTENEGRO_RANGE: return "Montenegro";
        case GS1_COMPANY_PREFIX_MOROCCO_RANGE: return "Morocco";
        case GS1_COMPANY_PREFIX_NETHERLANDS_RANGE: return "Netherlands";
        case GS1_COMPANY_PREFIX_NEW_ZEALAND_RANGE: return "New Zealand";
        case GS1_COMPANY_PREFIX_NICARAGUA_RANGE: return "Nicaragua";
        case GS1_COMPANY_PREFIX_NIGERIA_RANGE: return "Nigeria";
        case GS1_COMPANY_PREFIX_NORTH_KOREA_RANGE: return "North Korea";
        case GS1_COMPANY_PREFIX_NORWAY_RANGE: return "Norway";
        case GS1_COMPANY_PREFIX_OMAN_RANGE: return "Oman";
        case GS1_COMPANY_PREFIX_PAKISTAN_RANGE: return "Pakistan"; 
        case GS1_COMPANY_PREFIX_PARAGUAY_RANGE: return "Paraguay";
        case GS1_COMPANY_PREFIX_PERU_RANGE: return "Peru";
        case GS1_COMPANY_PREFIX_POLAND_RANGE: return "Poland";
        case GS1_COMPANY_PREFIX_PORTUGAL_RANGE: return "Portugal";
        case GS1_COMPANY_PREFIX_QATAR_RANGE: return "Qatar";
        case GS1_COMPANY_PREFIX_ROMANIA_RANGE: return "Romania";
        case GS1_COMPANY_PREFIX_RUSSIA_RANGE: return "Russia";
        case GS1_COMPANY_PREFIX_RWANDA_RANGE: return "Rwanda";
        case GS1_COMPANY_PREFIX_SAUDI_ARABIA_RANGE: return "Saudi Arabia";
        case GS1_COMPANY_PREFIX_SERBIA_RANGE: return "Serbia";
        case GS1_COMPANY_PREFIX_SINGAPORE_RANGE: return "Singapore";
        case GS1_COMPANY_PREFIX_SLOVAKIA_RANGE: return "Slovakia";
        case GS1_COMPANY_PREFIX_SLOVENIJA_RANGE: return "Slovenija";
        case GS1_COMPANY_PREFIX_SOUTH_AFRICA_RANGE: return "South Africa";
        case GS1_COMPANY_PREFIX_SOUTH_KOREA_RANGE: return "South Korea";
        case GS1_COMPANY_PREFIX_SPAIN_RANGE: return "Spain";
        case GS1_COMPANY_PREFIX_SRI_LANKA_RANGE: return "Sri Lanka";
        case GS1_COMPANY_PREFIX_SWEDEN_RANGE: return "Sweden";
        case GS1_COMPANY_PREFIX_SWITZERLAND_RANGE: return "Switzerland";
        case GS1_COMPANY_PREFIX_TAIWAN_RANGE: return "Taiwan";
        case GS1_COMPANY_PREFIX_TANZANIA_RANGE: return "Tanzania";
        case GS1_COMPANY_PREFIX_THAILAND_RANGE: return "Thailand";
        case GS1_COMPANY_PREFIX_TUNISIA_RANGE: return "Tunisia";
        case GS1_COMPANY_PREFIX_TURKIYE_RANGE: return "Türkiye";
        case GS1_COMPANY_PREFIX_TURKMENISTAN_RANGE: return "Turkmenistan";
        case GS1_COMPANY_PREFIX_UK_RANGE: return "United Kingdom";
        case GS1_COMPANY_PREFIX_UKRAINE_RANGE: return "Ukraine";
        case GS1_COMPANY_PREFIX_URUGUAY_RANGE: return "Uruguay";
        case GS1_COMPANY_PREFIX_UZBEKISTAN_RANGE: return "Uzbekistan";
        case GS1_COMPANY_PREFIX_VENEZUELA_RANGE: return "Venezuela";
        case GS1_COMPANY_PREFIX_VIETNAM_RANGE: return "Vietnam";
        case GS1_COMPANY_PREFIX_NONE: return "Not found";
        default: return "Unknown";
    }
}



char* GTIN_CompanyPrefix(GTIN* gt) {    

    if (gt->range != GTIN_PREFIX_GS1_COMPANY) {
        return NULL;
    }

    char gcp_string[4]; // 3 digits + null terminator
    strlcpy(gcp_string, gt->prefix, 4);

    int gcp_range = strtol(gcp_string, NULL, 10);
    GtinCompanyPrefixRange company_prefix_range = lookup_company_prefix(gcp_range);
    return GTIN_CompanyPrefixToString(company_prefix_range);
}